// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YallaPharm.Infrastructure.Data;

#nullable disable

namespace YallaPharm.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260204122242_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YallaPharm.Domain.Entities.Address", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("client_id");

                    b.Property<string>("GeolocationOfClientAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("geolocation_of_client_address");

                    b.Property<string>("Landmark")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("landmark");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("street");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("addresses", (string)null);
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.ApplicationMethod", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<string>("ApplicationMethodValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("application_method");

                    b.HasKey("Id");

                    b.ToTable("application_methods", (string)null);
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("ParentId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("parent_id");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.Client", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<short?>("Age")
                        .HasColumnType("smallint")
                        .HasColumnName("age");

                    b.Property<string>("ChildrensAge")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("childrens_age");

                    b.Property<string>("ContactType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("contact_type");

                    b.Property<int>("DiscountForClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("discount_for_client");

                    b.Property<string>("EconomicStanding")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("economic_standing");

                    b.Property<string>("FamilyStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("family_status");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gender");

                    b.Property<string>("GeolocationOfClientAddress")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("geolocation_of_client_address");

                    b.Property<bool>("HavingChildren")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("having_children");

                    b.Property<bool>("HavingElderly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("having_elderly");

                    b.Property<string>("Landmark")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("landmark");

                    b.Property<string>("Language")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("SocialUsername")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("social_username");

                    b.Property<string>("Street")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("street");

                    b.Property<string>("TakeIntoAccount")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("take_into_account");

                    b.Property<string>("Type")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.ClientAdult", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<short?>("Age")
                        .HasColumnType("smallint")
                        .HasColumnName("age");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("client_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gender");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("client_adults", (string)null);
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.ClientChildren", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<short?>("Age")
                        .HasColumnType("smallint")
                        .HasColumnName("age");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("client_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gender");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("client_childrens", (string)null);
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.Country", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("order_id");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.CourierOrder", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<string>("CourierId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("courier_id");

                    b.Property<string>("OrderHistoryId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("order_history_id");

                    b.HasKey("Id");

                    b.HasIndex("CourierId");

                    b.HasIndex("OrderHistoryId");

                    b.ToTable("courier_orders", (string)null);
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.ForWhom", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<string>("ForWhomValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("for_whom");

                    b.HasKey("Id");

                    b.ToTable("for_whom", (string)null);
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.OperatorOrder", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("operator_id");

                    b.Property<string>("OrderHistoryId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("order_history_id");

                    b.Property<string>("OrderOperatorId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("order_operator_id");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId");

                    b.HasIndex("OrderHistoryId");

                    b.HasIndex("OrderOperatorId");

                    b.ToTable("operator_orders", (string)null);
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<decimal?>("AmountWithDelivery")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount_with_delivery");

                    b.Property<decimal?>("AmountWithDiscount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount_with_discount");

                    b.Property<decimal?>("AmountWithMarkup")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount_with_markup");

                    b.Property<decimal?>("AmountWithoutDelivery")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount_without_delivery");

                    b.Property<decimal?>("AmountWithoutMarkup")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount_without_markup");

                    b.Property<string>("CityOrDistrict")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city_or_district");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("client_id");

                    b.Property<string>("ComesFrom")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("comes_from");

                    b.Property<string>("Comment")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("comment");

                    b.Property<string>("CommentForCourier")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("comment_for_courier");

                    b.Property<string>("CountryToDelivery")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country_to_delivery");

                    b.Property<string>("Courier")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("courier");

                    b.Property<string>("DeliveredAt")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("delivered_at");

                    b.Property<string>("DeliveryType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("delivery_type");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("discount");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("operator");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_number");

                    b.Property<decimal?>("Prepayment")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("prepayment");

                    b.Property<decimal?>("PriceForDeliveryOutsideTheCity")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price_for_delivery_outside_the_city");

                    b.Property<decimal?>("RemainingPayment")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("remaining_payment");

                    b.Property<decimal?>("RestPayment")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("rest_payment");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_cost");

                    b.Property<decimal?>("TotalOrderAmountExcludingDelivery")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_order_amount_excluding_delivery");

                    b.Property<string>("Type")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("idx_orders_client_id");

                    b.HasIndex("OrderNumber")
                        .HasDatabaseName("idx_orders_order_number");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.OrderHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<int?>("AmountOfDeliveryTime")
                        .HasColumnType("integer")
                        .HasColumnName("amount_of_delivery_time");

                    b.Property<int?>("AmountOfProcessingTime")
                        .HasColumnType("integer")
                        .HasColumnName("amount_of_processing_time");

                    b.Property<int?>("AmountOfTimeRespondClient")
                        .HasColumnType("integer")
                        .HasColumnName("amount_of_time_respond_client");

                    b.Property<string>("CallingAt")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("calling_at");

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("canceled_at");

                    b.Property<string>("CommentForCourier")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("comment_for_courier");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTime?>("ConsultedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consulted_at");

                    b.Property<DateTime?>("CourierAcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("courier_accepted_at");

                    b.Property<DateTime?>("CourierReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("courier_received_at");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<DateTime?>("DeliveredTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_time");

                    b.Property<DateTime?>("IndividualDeliveryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("individual_delivery_time");

                    b.Property<bool>("IsReturned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_returned");

                    b.Property<DateTime?>("LeadCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lead_created_at");

                    b.Property<string>("LongSearchReason")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("long_search_reason");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("message");

                    b.Property<int?>("MinutesForEntireProcessFinish")
                        .HasColumnType("integer")
                        .HasColumnName("minutes_for_entire_process_finish");

                    b.Property<int?>("MinutesForEntireProcessToPlacement")
                        .HasColumnType("integer")
                        .HasColumnName("minutes_for_entire_process_to_placement");

                    b.Property<DateTime?>("NotifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("notified_at");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("order_date");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("order_id");

                    b.Property<DateTime?>("OrderProcessingTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("order_processing_time");

                    b.Property<string>("PastState")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("past_state");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_method");

                    b.Property<string>("PaymentStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("payment_status");

                    b.Property<DateTime?>("PlacedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("placed_at");

                    b.Property<DateTime?>("PlacementAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("placement_at");

                    b.Property<int?>("PreviousStateBeforeRejectionState")
                        .HasColumnType("integer")
                        .HasColumnName("previous_state_before_rejection_state");

                    b.Property<DateTime?>("ReadyForShipmentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ready_for_shipment_at");

                    b.Property<string>("ReasonForOrderCancellation")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("reason_for_order_cancellation");

                    b.Property<string>("ReasonForOrderDelay")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("reason_for_order_delay");

                    b.Property<string>("ReasonForOrderRejection")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("reason_for_order_rejection");

                    b.Property<string>("ReasonForReturningTheOrder")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason_for_returning_the_order");

                    b.Property<DateTime?>("RequestDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("request_date");

                    b.Property<DateTime?>("RequestProcessingTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("request_processing_time");

                    b.Property<int?>("ReturnedProductsCount")
                        .HasColumnType("integer")
                        .HasColumnName("returned_products_count");

                    b.Property<DateTime?>("SearchingAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("searching_at");

                    b.Property<string>("State")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("state");

                    b.Property<DateTime?>("TimeForAcceptingRequest")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_for_accepting_request");

                    b.Property<DateTime?>("TimeInformCustomerAboutProduct")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_inform_customer_about_product");

                    b.Property<DateTime?>("TimeOfCompletionOfInquiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_of_completion_of_inquiry");

                    b.Property<DateTime?>("TimeToObtainClientApproval")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_to_obtain_client_approval");

                    b.Property<DateTime?>("TimeToSendCheckToClient")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_to_send_check_to_client");

                    b.Property<bool>("WasRejection")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("was_rejection");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("idx_order_histories_order_id");

                    b.HasIndex("State")
                        .HasDatabaseName("idx_order_histories_state");

                    b.ToTable("order_histories", (string)null);
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.OrgansAndSystem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<string>("OrgansAndSystemValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("organs_and_system");

                    b.HasKey("Id");

                    b.ToTable("organs_and_systems", (string)null);
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.PackagingMaterial", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<string>("PackagingMaterialValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("packaging_material");

                    b.HasKey("Id");

                    b.ToTable("packaging_materials", (string)null);
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.PackagingType", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("packaging_types", (string)null);
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.PackagingUnit", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("packaging_units", (string)null);
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.PaymentMethod", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("payment_methods", (string)null);
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.Pharmacy", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<string>("Contact")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("contact");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<string>("GeolocationLink")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("geolocation_link");

                    b.Property<bool>("IsAbroad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_abroad");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_required");

                    b.Property<string>("Landmark")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("landmark");

                    b.Property<decimal?>("Markup")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("markup");

                    b.Property<string>("MarkupType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("markup_type");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PayoutMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payout_method");

                    b.HasKey("Id");

                    b.ToTable("pharmacies", (string)null);
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.PharmacyContact", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("contact");

                    b.Property<string>("ContactType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("contact_type");

                    b.Property<string>("PharmacyId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("pharmacy_id");

                    b.HasKey("Id");

                    b.HasIndex("PharmacyId");

                    b.ToTable("pharmacy_contacts", (string)null);
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.PharmacyOrder", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("order_id");

                    b.Property<string>("PharmacyId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("pharmacy_id");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("PharmacyId");

                    b.ToTable("pharmacy_orders", (string)null);
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.PreparationColor", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<string>("PreparationColorValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("preparation_color");

                    b.HasKey("Id");

                    b.ToTable("preparation_colors", (string)null);
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.PreparationMaterial", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<string>("PreparationMaterialValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("preparation_material");

                    b.HasKey("Id");

                    b.ToTable("preparation_materials", (string)null);
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<int?>("AgeFrom")
                        .HasColumnType("integer")
                        .HasColumnName("age_from");

                    b.Property<int?>("AgeTo")
                        .HasColumnType("integer")
                        .HasColumnName("age_to");

                    b.Property<string>("AgeType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("age_type");

                    b.Property<int?>("CountOnPackage")
                        .HasColumnType("integer")
                        .HasColumnName("count_on_package");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("country");

                    b.Property<bool>("Dificit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("dificit");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("dosage");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_required");

                    b.Property<string>("LinkProduct")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("link_product");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("PackagingUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("packaging_unit");

                    b.Property<string>("PathImage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("path_image");

                    b.Property<decimal>("PriceWithMarkup")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price_with_markup");

                    b.Property<decimal?>("PriceWithoutMarkup")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price_without_markup");

                    b.Property<string>("ReleaseForm")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("release_form");

                    b.Property<string>("State")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<string>("TypeOfPackaging")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type_of_packaging");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("idx_products_name");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.ProductHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<decimal?>("AmountWithMarkup")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount_with_markup");

                    b.Property<decimal?>("AmountWithoutMarkup")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount_without_markup");

                    b.Property<DateTime?>("ArrivalDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("arrival_date");

                    b.Property<string>("Comment")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("comment");

                    b.Property<short?>("Count")
                        .HasColumnType("smallint")
                        .HasColumnName("count");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsReturned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_returned");

                    b.Property<string>("LongSearchReason")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("long_search_reason");

                    b.Property<string>("Message")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("message");

                    b.Property<string>("PharmacyOrderId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("pharmacy_order_id");

                    b.Property<string>("ProductId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("product_id");

                    b.Property<string>("ReturnReason")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("return_reason");

                    b.Property<string>("ReturnTo")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("return_to");

                    b.Property<int?>("ReturnedCount")
                        .HasColumnType("integer")
                        .HasColumnName("returned_count");

                    b.HasKey("Id");

                    b.HasIndex("PharmacyOrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("product_histories", (string)null);
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.ProductProvider", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("product_id");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("provider_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProviderId");

                    b.ToTable("product_providers", (string)null);
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.ProductTemplate", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<string>("ActiveIngredient")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("active_ingredient");

                    b.Property<short?>("AgeFrom")
                        .HasColumnType("smallint")
                        .HasColumnName("age_from");

                    b.Property<short?>("AgeTo")
                        .HasColumnType("smallint")
                        .HasColumnName("age_to");

                    b.Property<string>("ApplicationMethodId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("application_method_id");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("category_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("comment");

                    b.Property<string>("ContraindicationForUse")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("contraindication_for_use");

                    b.Property<string>("Dosage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("dosage");

                    b.Property<string>("DosageUnit")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("dosage_unit");

                    b.Property<string>("DriedFruit")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("dried_fruit");

                    b.Property<string>("ForAllergySufferers")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("for_allergy_sufferers");

                    b.Property<string>("ForChildren")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("for_children");

                    b.Property<string>("ForDiabetics")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("for_diabetics");

                    b.Property<string>("ForDriver")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("for_driver");

                    b.Property<string>("ForPregnantWomen")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("for_pregnant_women");

                    b.Property<string>("ForWhomId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("for_whom_id");

                    b.Property<string>("IndicationForUse")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("indication_for_use");

                    b.Property<string>("Instructions")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("instructions");

                    b.Property<int?>("MinimumQuantityPerPiece")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_quantity_per_piece");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Nickname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nickname");

                    b.Property<string>("OrgansAndSystemsId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("organs_and_systems_id");

                    b.Property<string>("PackQuantityOrDrugVolume")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("pack_quantity_or_drug_volume");

                    b.Property<string>("PackagingMaterialId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("packaging_material_id");

                    b.Property<string>("PackagingUnit")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("packaging_unit");

                    b.Property<string>("PreparationColorId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("preparation_color_id");

                    b.Property<string>("PreparationMaterialId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("preparation_material_id");

                    b.Property<string>("PreparationTaste")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("preparation_taste");

                    b.Property<string>("ScopeOfApplicationId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("scope_of_application_id");

                    b.Property<string>("SeasonOfApplication")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("season_of_application");

                    b.Property<string>("Symptom")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("symptom");

                    b.Property<string>("TimeOfApplicationId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("time_of_application_id");

                    b.Property<string>("VacationCondition")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("vacation_condition");

                    b.Property<string>("WithCaution")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("with_caution");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationMethodId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ForWhomId");

                    b.HasIndex("OrgansAndSystemsId");

                    b.HasIndex("PackagingMaterialId");

                    b.HasIndex("PreparationColorId");

                    b.HasIndex("PreparationMaterialId");

                    b.HasIndex("ScopeOfApplicationId");

                    b.HasIndex("TimeOfApplicationId");

                    b.ToTable("product_templates", (string)null);
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.Provider", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("contact");

                    b.Property<string>("ContactType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("contact_type");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<string>("LinkFromWhereFoundAbroad")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("link_from_where_found_abroad");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("providers", (string)null);
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.ReleaseForm", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("release_forms", (string)null);
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.ScopeOfApplication", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<string>("ScopeOfApplicationValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("scope_of_application");

                    b.HasKey("Id");

                    b.ToTable("scope_of_applications", (string)null);
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.TimeOfApplication", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<string>("TimeOfApplicationValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_of_application");

                    b.HasKey("Id");

                    b.ToTable("time_of_applications", (string)null);
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.Address", b =>
                {
                    b.HasOne("YallaPharm.Domain.Entities.Client", "Client")
                        .WithMany("Addresses")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.Category", b =>
                {
                    b.HasOne("YallaPharm.Domain.Entities.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.ClientAdult", b =>
                {
                    b.HasOne("YallaPharm.Domain.Entities.Client", "Client")
                        .WithMany("Adults")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.ClientChildren", b =>
                {
                    b.HasOne("YallaPharm.Domain.Entities.Client", "Client")
                        .WithMany("Childrens")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.Country", b =>
                {
                    b.HasOne("YallaPharm.Domain.Entities.Order", "Order")
                        .WithMany("Countries")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.CourierOrder", b =>
                {
                    b.HasOne("YallaPharm.Domain.Entities.User", "Courier")
                        .WithMany("CourierOrders")
                        .HasForeignKey("CourierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YallaPharm.Domain.Entities.OrderHistory", "OrderHistory")
                        .WithMany("CourierOrders")
                        .HasForeignKey("OrderHistoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Courier");

                    b.Navigation("OrderHistory");
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.OperatorOrder", b =>
                {
                    b.HasOne("YallaPharm.Domain.Entities.User", "Operator")
                        .WithMany("OperatorOrders")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YallaPharm.Domain.Entities.OrderHistory", "OrderHistory")
                        .WithMany("OperatorOrders")
                        .HasForeignKey("OrderHistoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("YallaPharm.Domain.Entities.User", "OrderOperator")
                        .WithMany()
                        .HasForeignKey("OrderOperatorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Operator");

                    b.Navigation("OrderHistory");

                    b.Navigation("OrderOperator");
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.Order", b =>
                {
                    b.HasOne("YallaPharm.Domain.Entities.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.OrderHistory", b =>
                {
                    b.HasOne("YallaPharm.Domain.Entities.Order", "Order")
                        .WithOne("OrderHistory")
                        .HasForeignKey("YallaPharm.Domain.Entities.OrderHistory", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.PharmacyContact", b =>
                {
                    b.HasOne("YallaPharm.Domain.Entities.Pharmacy", "Pharmacy")
                        .WithMany("PharmacyContacts")
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pharmacy");
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.PharmacyOrder", b =>
                {
                    b.HasOne("YallaPharm.Domain.Entities.Order", "Order")
                        .WithMany("PharmacyOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YallaPharm.Domain.Entities.Pharmacy", "Pharmacy")
                        .WithMany("PharmacyOrders")
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Order");

                    b.Navigation("Pharmacy");
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.ProductHistory", b =>
                {
                    b.HasOne("YallaPharm.Domain.Entities.PharmacyOrder", "PharmacyOrder")
                        .WithMany("ProductHistories")
                        .HasForeignKey("PharmacyOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YallaPharm.Domain.Entities.Product", "Product")
                        .WithMany("ProductHistories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("PharmacyOrder");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.ProductProvider", b =>
                {
                    b.HasOne("YallaPharm.Domain.Entities.Product", "Product")
                        .WithMany("ProductProviders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YallaPharm.Domain.Entities.Provider", "Provider")
                        .WithMany("ProductProviders")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.ProductTemplate", b =>
                {
                    b.HasOne("YallaPharm.Domain.Entities.ApplicationMethod", "ApplicationMethod")
                        .WithMany("ProductTemplates")
                        .HasForeignKey("ApplicationMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YallaPharm.Domain.Entities.Category", "Category")
                        .WithMany("ProductTemplates")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YallaPharm.Domain.Entities.ForWhom", "ForWhom")
                        .WithMany("ProductTemplates")
                        .HasForeignKey("ForWhomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YallaPharm.Domain.Entities.OrgansAndSystem", "OrgansAndSystems")
                        .WithMany("ProductTemplates")
                        .HasForeignKey("OrgansAndSystemsId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("YallaPharm.Domain.Entities.PackagingMaterial", "PackagingMaterial")
                        .WithMany("ProductTemplates")
                        .HasForeignKey("PackagingMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YallaPharm.Domain.Entities.PreparationColor", "PreparationColor")
                        .WithMany("ProductTemplates")
                        .HasForeignKey("PreparationColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YallaPharm.Domain.Entities.PreparationMaterial", "PreparationMaterial")
                        .WithMany("ProductTemplates")
                        .HasForeignKey("PreparationMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YallaPharm.Domain.Entities.ScopeOfApplication", "ScopeOfApplication")
                        .WithMany("ProductTemplates")
                        .HasForeignKey("ScopeOfApplicationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("YallaPharm.Domain.Entities.TimeOfApplication", "TimeOfApplication")
                        .WithMany("ProductTemplates")
                        .HasForeignKey("TimeOfApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationMethod");

                    b.Navigation("Category");

                    b.Navigation("ForWhom");

                    b.Navigation("OrgansAndSystems");

                    b.Navigation("PackagingMaterial");

                    b.Navigation("PreparationColor");

                    b.Navigation("PreparationMaterial");

                    b.Navigation("ScopeOfApplication");

                    b.Navigation("TimeOfApplication");
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.ApplicationMethod", b =>
                {
                    b.Navigation("ProductTemplates");
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("ProductTemplates");
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.Client", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Adults");

                    b.Navigation("Childrens");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.ForWhom", b =>
                {
                    b.Navigation("ProductTemplates");
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.Order", b =>
                {
                    b.Navigation("Countries");

                    b.Navigation("OrderHistory");

                    b.Navigation("PharmacyOrders");
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.OrderHistory", b =>
                {
                    b.Navigation("CourierOrders");

                    b.Navigation("OperatorOrders");
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.OrgansAndSystem", b =>
                {
                    b.Navigation("ProductTemplates");
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.PackagingMaterial", b =>
                {
                    b.Navigation("ProductTemplates");
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.Pharmacy", b =>
                {
                    b.Navigation("PharmacyContacts");

                    b.Navigation("PharmacyOrders");
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.PharmacyOrder", b =>
                {
                    b.Navigation("ProductHistories");
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.PreparationColor", b =>
                {
                    b.Navigation("ProductTemplates");
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.PreparationMaterial", b =>
                {
                    b.Navigation("ProductTemplates");
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.Product", b =>
                {
                    b.Navigation("ProductHistories");

                    b.Navigation("ProductProviders");
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.Provider", b =>
                {
                    b.Navigation("ProductProviders");
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.ScopeOfApplication", b =>
                {
                    b.Navigation("ProductTemplates");
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.TimeOfApplication", b =>
                {
                    b.Navigation("ProductTemplates");
                });

            modelBuilder.Entity("YallaPharm.Domain.Entities.User", b =>
                {
                    b.Navigation("CourierOrders");

                    b.Navigation("OperatorOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
